# Generated by Django 2.2.13 on 2021-07-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guozhi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(max_length=20, verbose_name='环境')),
                ('database_name', models.CharField(max_length=50, verbose_name='数据库名')),
                ('table_name', models.CharField(max_length=50, verbose_name='表名')),
                ('operational_data', models.TextField(verbose_name='执行语句')),
                ('user', models.CharField(max_length=20, verbose_name='用户名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.IntegerField(choices=[(0, '失败'), (1, '成功')], default=1, verbose_name='执行状态')),
            ],
            options={
                'verbose_name': 'sql执行记录',
                'verbose_name_plural': 'sql执行记录',
                'db_table': 'guozhi_operation_log',
            },
        ),
        migrations.CreateModel(
            name='Sqlscripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('type', models.CharField(choices=[(1, 'sql'), (2, 'shell')], max_length=10, verbose_name='类型')),
                ('content', models.FileField(upload_to='files', verbose_name='文件内容')),
                ('creator', models.CharField(max_length=20, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '果之sql脚本',
                'verbose_name_plural': '果之sql脚本',
                'db_table': 'guozhi_sqlscripts',
            },
        ),
    ]
