# Generated by Django 2.2.13 on 2021-07-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guozhi', '0002_operationlog_sqlscripts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlOperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(max_length=20, verbose_name='环境')),
                ('database_name', models.CharField(max_length=50, verbose_name='数据库名')),
                ('table_name', models.CharField(max_length=50, verbose_name='表名')),
                ('operational_data', models.CharField(max_length=500, verbose_name='执行语句')),
                ('user', models.CharField(max_length=20, verbose_name='用户名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.IntegerField(choices=[(0, '失败'), (1, '成功')], default=1, verbose_name='执行状态')),
            ],
            options={
                'verbose_name': 'sql执行记录',
                'verbose_name_plural': 'sql执行记录',
                'db_table': 'guozhi_operation_log',
            },
        ),
        migrations.DeleteModel(
            name='OperationLog',
        ),
    ]
