# Generated by Django 2.2.13 on 2021-07-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guozhi', '0003_auto_20210719_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqloperationlog',
            name='operational_data',
            field=models.TextField(verbose_name='执行语句'),
        ),
    ]
