# Generated by Django 2.2.13 on 2021-07-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guozhi', '0005_sqloperationlog_error_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqloperationlog',
            name='table_name',
        ),
    ]
