# Generated by Django 2.2.13 on 2021-07-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guozhi', '0006_remove_sqloperationlog_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqloperationlog',
            name='error_info',
            field=models.CharField(default='Null', max_length=255, verbose_name='错误信息'),
        ),
    ]
