# Generated by Django 2.2.13 on 2021-07-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guozhi', '0008_auto_20210720_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqloperationlog',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '失败'), (1, '成功')], default=1, verbose_name='执行状态'),
        ),
    ]
