# Generated by Django 2.2.13 on 2021-07-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guozhi', '0010_auto_20210720_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqloperationlog',
            name='status',
            field=models.IntegerField(choices=[(0, '失败'), (1, '成功')], default=1, verbose_name='执行状态'),
        ),
    ]
