# Generated by Django 2.2.13 on 2021-08-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbserverconfig',
            name='db_mark',
            field=models.CharField(max_length=200, null=True, verbose_name='备注'),
        ),
    ]
