# Generated by Django 2.2.13 on 2021-07-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('client_name', models.CharField(max_length=50, verbose_name='连接名称')),
                ('environment', models.SmallIntegerField(choices=[(0, '生产'), (1, '测试'), (2, '开发'), (3, '演示'), (4, '验收')], default=1, verbose_name='环境')),
                ('host', models.CharField(max_length=50, verbose_name='ip地址')),
                ('database_type', models.SmallIntegerField(choices=[(0, 'mysql'), (1, 'sqlserver')], default=0, verbose_name='数据库类型')),
                ('database_version', models.CharField(max_length=50, verbose_name='数据库版本')),
                ('use', models.CharField(max_length=200, verbose_name='用途')),
                ('database_name', models.CharField(default=None, max_length=50, verbose_name='数据库名称')),
                ('username', models.CharField(max_length=32, verbose_name='登录账户')),
                ('password', models.CharField(max_length=64, verbose_name='登录密码')),
                ('port', models.PositiveIntegerField(verbose_name='登录端口号')),
            ],
            options={
                'verbose_name': '数据库连接信息',
                'verbose_name_plural': '数据库连接信息',
                'db_table': 'dbms_database_info',
                'ordering': ['update_time'],
            },
        ),
        migrations.CreateModel(
            name='SqlOperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(max_length=20, verbose_name='环境')),
                ('database_name', models.CharField(max_length=50, verbose_name='数据库名')),
                ('operational_data', models.TextField(verbose_name='执行语句')),
                ('user', models.CharField(max_length=20, verbose_name='用户名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.IntegerField(choices=[(0, '失败'), (1, '成功')], default=1, verbose_name='执行状态')),
                ('error_info', models.CharField(default=None, max_length=255, verbose_name='message')),
            ],
            options={
                'verbose_name': 'sql执行记录',
                'verbose_name_plural': 'sql执行记录',
                'db_table': 'dbms_operation_log',
            },
        ),
        migrations.CreateModel(
            name='Sqlscripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('type', models.CharField(choices=[(1, 'sql'), (2, 'shell')], max_length=10, verbose_name='类型')),
                ('content', models.FileField(upload_to='files', verbose_name='文件内容')),
                ('creator', models.CharField(max_length=20, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '果之sql脚本',
                'verbose_name_plural': '果之sql脚本',
                'db_table': 'dbms_sqlscripts',
            },
        ),
    ]
