# Generated by Django 2.2.13 on 2021-07-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0002_accounts_sqloperationlog_sqlscripts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='database_type',
            field=models.IntegerField(choices=[(0, 'mysql'), (1, 'sqlserver')], default=0, verbose_name='数据库类型'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='environment',
            field=models.IntegerField(choices=[(0, '生产'), (1, '测试'), (2, '开发'), (3, '演示'), (4, '验收')], default=1, verbose_name='环境'),
        ),
    ]
