# Generated by Django 2.2.13 on 2021-07-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0003_auto_20210721_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='create_user',
            field=models.CharField(default=None, max_length=20, verbose_name='创建者'),
            preserve_default=False,
        ),
    ]
