# Generated by Django 2.2.13 on 2021-07-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0005_auto_20210721_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlscripts',
            name='create_user',
            field=models.CharField(default=None, max_length=20, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='create_user',
            field=models.CharField(default=None, max_length=20, verbose_name='创建者'),
        ),
    ]
