# Generated by Django 2.2.13 on 2021-07-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0006_auto_20210721_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqlscripts',
            name='create_user',
        ),
    ]
