# Generated by Django 2.2.13 on 2021-07-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0007_remove_sqlscripts_create_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='create_user',
            field=models.CharField(max_length=20, verbose_name='创建者'),
        ),
    ]
