# Generated by Django 2.2.13 on 2021-07-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0008_auto_20210721_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='environment',
            field=models.IntegerField(choices=[(0, '生产'), (1, '测试'), (2, '开发'), (3, '演示'), (4, '验收')], default=1, verbose_name='环境'),
        ),
    ]
