# Generated by Django 2.2.13 on 2021-08-18 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0012_auto_20210817_1827'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dbserverconfig',
            table='dbms_config_info',
        ),
    ]
