# Generated by Django 2.2.13 on 2021-08-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0013_auto_20210818_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbserverconfig',
            name='db_password',
            field=models.CharField(max_length=128, verbose_name='登录密码'),
        ),
    ]
