# Generated by Django 2.2.13 on 2021-08-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0016_auto_20210818_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbserverconfig',
            name='db_mark',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='dbserverconfig',
            name='db_version',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='数据库版本'),
        ),
    ]
