# Generated by Django 2.2.13 on 2021-08-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0017_auto_20210818_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbserverconfig',
            name='db_version',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='数据库版本'),
        ),
    ]
